name: LiveScribe

options:
  bundleIdPrefix: com.livescribe
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_STYLE: Automatic

targets:
  LiveScribe:
    type: application
    platform: macOS

    sources:
      - path: LiveScribe
        excludes:
          - Resources/Info.plist
          - Resources/LiveScribe.entitlements

    info:
      path: LiveScribe/Resources/Info.plist
      properties:
        LSUIElement: YES
        NSHighResolutionCapable: YES
        NSPrincipalClass: NSApplication
        NSScreenCaptureUsageDescription: "LiveScribe needs Screen Recording access to capture audio playing on your Mac."
        LSMinimumSystemVersion: "13.0"

    entitlements:
      path: LiveScribe/Resources/LiveScribe.entitlements
      properties:
        com.apple.security.app-sandbox: NO

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.livescribe.app
        INFOPLIST_FILE: LiveScribe/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: LiveScribe/Resources/LiveScribe.entitlements

    scheme:
      environmentVariables:
        LIVESCRIBE_SERVER_SCRIPT: /Users/Maciek/reel_transcriber/LiveScribe/PythonServer/server.py
        LIVESCRIBE_PYTHON_BIN: /Users/Maciek/reel_transcriber/LiveScribe/PythonServer/venv/bin/python3
